DROP TABLE PAGAMENTO;

CREATE TABLE PAGAMENTO (
    IDPAGAMENTO    NUMBER PRIMARY KEY,
    TIPOPAGAMENTO  NUMBER NOT NULL,
    DATA           VARCHAR2(15) NOT NULL,
    VALOR          NUMBER(10, 2) NOT NULL,
    STATUS         VARCHAR2(50),
    IDCLIENTE      NUMBER NOT NULL
);

