DROP TABLE PAGAMENTO;

-- CRIAÇÃO DA TABELA PAGAMENTO
CREATE TABLE PAGAMENTO (
    IDPAGAMENTO    NUMBER PRIMARY KEY,
    TIPOPAGAMENTO  NUMBER NOT NULL,
    DATA           VARCHAR2(15) NOT NULL,
    VALOR          NUMBER(10, 2) NOT NULL,
    STATUS         VARCHAR2(50),
    IDCLIENTE      NUMBER NOT NULL
);

-- CRIAÇÃO DA CHAVE ESTRAGEIRA (RELACIONAMENTO COM A TABELA CLIENTE)
ALTER TABLE PAGAMENTO
ADD CONSTRAINT FK_PAGAMENTO_CLIENTE FOREIGN KEY (IDCLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

