DROP TABLE COMPRA;

CREATE TABLE COMPRA(
    ID_COMPRA           NUMBER(10,0) PRIMARY KEY,
	VALOR               NUMBER(10,2) NOT NULL,
	ID_CLIENTE          NUMBER(5,0) NOT NULL,
	ID_CARTAO           NUMBER(5,0) NOT NULL
	);

ALTER TABLE COMPRA
    ADD CONSTRAINT id_usuario_fk FOREIGN KEY(ID_CLIENTE)
REFERENCES cadastro (ID_CLIENTE);

ALTER TABLE COMPRA
    ADD CONSTRAINT id_cartaocredito_fk FOREIGN KEY(IDCARTAOCREDITO)
REFERENCES cartaocredito (IDCARTAOCREDITO);