CREATE TABLE COMPRA(
    ID_COMPRA           NUMBER(10,0) PRIMARY KEY,
	VALOR               NUMBER(10,2) NOT NULL,
	ID_USUARIO          NUMBER(5,0) NOT NULL,
	ID_CARTAO           NUMBER(5,0) NOT NULL
	);

DROP TABLE COMPRA;